name: Build iOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
  
      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Clean Build
        run: xcodebuild clean -project Nyxian.xcodeproj -scheme Nyxian

      - name: Build and Archive
        run: |
          xcodebuild clean archive \
            -project Nyxian.xcodeproj \
            -scheme Nyxian \
            -archivePath ${{ github.workspace }}/build/Nyxian.xcarchive \
            -destination "generic/platform=iOS" \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            DEVELOPMENT_TEAM=""

      - name: Export .ipa
        run: |
          xcodebuild -exportArchive \
            -archivePath ${{ github.workspace }}/build/Nyxian.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath ${{ github.workspace }}/build \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            DEVELOPMENT_TEAM=""

      - name: Upload .ipa artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nyxian App IPA
          path: build/*.ipa
